### ISSUE TITLE
breaks when using iphone chrome

### ISSUE THREAD

**Issue by cmosguy** [jsdom/abab#15]
Hey @jeffcarp ,

This package is actually a dependency in a few other packages, specifically [pwstrength-bootstrap](https://github.com/ablanco/jquery.pwstrength.bootstrap)

The problem is when everything is compiled down in es6, etc. (browserify) some browsers do no support the lines you have here:

https://github.com/jsdom/abab/blob/master/index.js#L3

We keep getting an error that says 
`
Uncaught SyntaxError: Use of const in strict mode.
`

Can you fix this and remove the use of the "const" so that it is compatible?

Thanks!
Adam

**Comment by Joris-van-der-Wel** [comment]
You could try using https://github.com/thlorenz/es6ify

**Comment by jeffcarp** [comment]
Hi @cmosguy, thanks for bringing this up. I [asked about this on Twitter](https://twitter.com/jcarp/status/682053731563651072) and my current plan is:

1. Short term: replace `const` with `var`
2. Long term: introduce Babel as a precompile step so we can use ES6 features but publish ES5 to npm

**Comment by cmosguy** [comment]
Hey @jeffcarp thanks for your quick response. How quickly can you fix this and tag update?

**Comment by jeffcarp** [comment]
It's out as `1.0.2`! 

Changes: https://github.com/jsdom/abab/compare/1.0.1...1.0.2

Feel free to re-open if anything comes up!
