### ISSUE TITLE
remove `let` from

### ISSUE THREAD

**Issue by cmosguy** [jsdom/abab#18]
Hey @jeffcarp ,

Hope you don't mind me being more of a PITA, could up update one more line:

https://github.com/jsdom/abab/blob/master/lib/btoa.js#L7

We need to also remove the `let` statement here.  The code will break  on iOS devices for both safari and chrome.  

Thanks!
Adam

**Comment by jeffcarp** [comment]
No problem at all, I can push an update next time I have time to work on this.

**Comment by jeffcarp** [comment]
Fixed in [1.0.3](https://github.com/jsdom/abab/releases/tag/1.0.3)!
