### ISSUE TITLE
Add missing license file

### ISSUE THREAD

**Issue by 0x326** [jsdom/abab#19]
This looks like a cool project.  However, this project is missing a license file which is necessary for others to build upon this repo in compliance with U.S. copyright law.  A contributor can easily license this repo through the GitHub web interface by creating a file named `LICENSE` then selecting a template license from the menu that appears to the left.  I highly recommend the ‘MIT license’, the ‘BSD 2-clause license’, the ‘BSD 3-clause license’, the ‘ISC license’, the ‘Apache 2.0 license’, or another “permissive” license.  I highly recommend against “copyleft” licenses, such as the GNU GPL, since they do not reflect the true spirit of open source software and since such licenses are harmful to commercial software projects that would like to include the licensed work.  So, to foster the integration of this code into other projects, I recommend the MIT license be given to this work.

Also, if this repo builds upon [w3c/web-platform-tests](https://github.com/w3c/web-platform-tests/blob/master/html/webappapis/atob/base64.html) as the README suggests, a copy of [its license](https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md#w3c-3-clause-bsd-license) must be included as well.

**Comment by jeffcarp** [comment]
Thanks! I reproduced the BSD license from the WPT in 4d845984c8802606e27dc31e241081f6fec465cc.

**Comment by 0x326** [comment]
Thanks for reproducing w3c's license.  

On a related note, perhaps the field the `license` field in [`package.json`](https://github.com/jsdom/abab/blob/master/package.json) should be changed to `"UNLICENSED"` since the contributions specific to this repo do not appear released under any license

**Comment by jeffcarp** [comment]
@0x326 if I released the contributions specific to this repo under the BSD 3-clause license, same as WPT, would it be reasonable to change the `license` field in  `package.json` to BSD?

**Comment by 0x326** [comment]
@jeffcarp It would actually be `BSD-3-Clause`, according to the [SPDX License List](https://spdx.org/licenses/BSD-3-Clause.html).  If you would like to add the license text and change the license field in `package.json`, I would be happy to incorporate this code into a project I am working on.

**Comment by jeffcarp** [comment]
@0x326 sorry for the reply latency

> add the license text

What do you mean by this specifically? Making it more clear in `LICENSE.md` that this code is released under `BSD-3-Clause`?

**Comment by 0x326** [comment]
@jeffcarp I think the license file reads as if it only reproduces W3C's license.  It seems to not mention a release of the changes made in this repo.  I could be wrong, as I am not a lawyer, but all I really need to know is that you intend to release this repo under the same license.  If that is the case, then I can be confident in building upon your work in compliance with U.S. copyright law.

**Comment by jeffcarp** [comment]
@0x326 hey sorry for the late reply again - I'm going to change the license to call out the changes made in this repo specifically being released under 3-Clause BSD.

**Comment by jeffcarp** [comment]
@0x326 I can't add you as a reviewer since you're not a member of this repo, but could you take a look at #20 when you get a chance?
