### ISSUE TITLE
Investigate browser testing story

### ISSUE THREAD

**Issue by jeffcarp** [jsdom/abab#2]
It would be useful to verify `abab`'s implementations against real-world browsers. I know Saucelabs has JS unit testing, but it's not free.

For reference, after this issue is resolved:

- [x] Update compatibility section in README to list specific browsers and version supported

**Comment by Joris-van-der-Wel** [comment]
Saucelabs is free for opensource projects. I have used js unit testing with them before.

I have tried using it with both testem and karma. Testem is great to use on your own machine, but it is hard to get to work properly on your own machine, so at the end I used karma.

Here is the project I used it in: https://github.com/Joris-van-der-Wel/name-overrides-builtin
Relevant files are:  `sauce-browsers.js`, `Gruntfile.js` (to avoid launching all the browsers at the same time), `karma.conf-ci.js`. I start the saucelabs testing using `grunt ci --force`.

**Comment by jeffcarp** [comment]
Oops, my mistake :speak_no_evil: Thanks for the correction and the example @Joris-van-der-Wel, I'll go ahead and start investigating Sauce + karma.

**Comment by jeffcarp** [comment]
Solved by @just-boris in #8!

I updated the compatibility section in the README (6ddbb3d091e2862248d21256c66c9c5bd6ef682d) but it still doesn't mention the versions of browsers we support since we only test against the latest versions in Sauce.
