### ISSUE TITLE
CI is broken due to Sauce credentials

### ISSUE THREAD

**Issue by jeffcarp** [jsdom/abab#21]
See https://travis-ci.org/jsdom/abab/builds/217634257

**Comment by Joris-van-der-Wel** [comment]
By the way, it is possible to run firefox and chrome directly on travis, without saucelabs. (but not internet explorer). This could be something worth considering if saucelabs gives you a lot of trouble? Here is an example: https://travis-ci.org/Joris-van-der-Wel/karma-mocha-webworker

**Comment by jeffcarp** [comment]
Thank you so much for the example @Joris-van-der-Wel (and sorry this is 8 months late... haha)

**Comment by Joris-van-der-Wel** [comment]
Haha :D
I'm glad it works. 
I wonder if firefox still crashes inside of docker containers
