### ISSUE TITLE
Reference "Forgiving base64"-section of the Infra spec

### ISSUE THREAD

**Issue by Zirro** [jsdom/abab#23]
The base64 algorithms were recently moved to the [Infra spec](https://infra.spec.whatwg.org/#forgiving-base64), which the HTML spec now [references](https://html.spec.whatwg.org/multipage/webappapis.html#atob).

In the process it seems like certain changes were made, probably requiring changes to the implementation as well.

**Comment by jeffcarp** [comment]
Thanks, will make a separate bug to audit the implementation against the newest version of the spec.
