### ISSUE TITLE
Is IE 11 supported?

### ISSUE THREAD

**Issue by SilentImp** [jsdom/abab#28]
Hi, I have got an error:

> window.onerror · Ongeldig teken
> node_modules/abab/lib/btoa.js:10
> 

~~~javascript 
09. // String conversion as required by Web IDL.
10. s = `${s}`;
~~~

Window 7, IE 11.
Looks like the luck of support of the IE 11.
But not 100% sure about it.

I am using it this way:

~~~javascript
import { btoa } from 'abab';

const getURL = ({ backURL, query, type, host }) => {
  let url = `https://${host}${`/connect/${type}`}`;
  if (backURL) {
    url = `${url}?state=${btoa(
      JSON.stringify({
        'social-login-flow': 'SERVICE_REQUEST_CREATION',
        // eslint-disable-next-line prettier/prettier
        'redirect-url': `https://${host}${backURL}${query}`.replace(/([^:]\/)\/+/g, '$1')
      })
    )}`;
  }
  return url;
};
~~~

**Comment by SilentImp** [comment]
None reproducible in win 10 edge ie11 simulation.

**Comment by SilentImp** [comment]
was reproduced in real ie11 on win 7.

**Comment by jeffcarp** [comment]
The README is unclear whether IE11 should be supported ("Compatibility: Node.js version 3+ and all major browsers."), but currently I do not intend to support this module in any Internet Explorer. Is transpiling an option for your use case?

**Comment by jeffcarp** [comment]
Closing old issue
