### ISSUE TITLE
Update license text to proper BSD-3-Clause

### ISSUE THREAD

**Issue by PhilippWendler** [jsdom/abab#31]
The https://github.com/jsdom/abab/blob/master/LICENSE.md file contains the "W3C 3-clause BSD License", but https://github.com/jsdom/abab/blob/master/package.json mentions the regular `BSD-3-clause`. This is especially confusing because `LICENSE.md` also contains a link to https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md#w3c-3-clause-bsd-license, claiming that the link points to the W3C variant, but the link target shows only the unmodified license (the W3C variant got removed in https://github.com/web-platform-tests/wpt/commit/402c8a6279626a01c1e735b02223245b3fc2d4a4#diff-37854d19817c792316d481f5beb93cc7).

So I suggest to update `LICENSE.md` to also use the regular BSD-3-clause license (it only differs in wording) and remove all references to the W3C variant and the link to that other repo. This makes it easier for users of the package to confirm the license status.

**Comment by jeffcarp** [comment]
Sounds good. I don't know when I'll be able to get to this, but PRs welcome.
