### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by jeffcarp** [jsdom/abab#6]
@domenic I think I might need your help to enable Travis on this repository (I can't change the settings).

https://travis-ci.org/jsdom/abab

**Comment by domenic** [comment]
I think I set it up, although maybe it needs another push before it actually tries building.

**Comment by jeffcarp** [comment]
Thanks! I will wait and observe.

**Comment by jeffcarp** [comment]
It's building :fireworks: :flags:
