### ISSUE TITLE
Moving out of the jsdom org, and/or deprecating this package?

### ISSUE THREAD

**Issue by domenic** [jsdom/abab#88]
Since Node.js added native `atob()` and `btoa()`, I'm working on moving jsdom to use those instead of this package. (Hooray for progress!!)

As such, it'd probably be best to move this out of the jsdom organization. Or, if nobody wants to maintain it anymore, we can just deprecate it. (Clean up the main branch, and use `npm deprecate`.)

We shouldn't do `npm deprecate` until a new jsdom version is published, at least.

**Comment by jeffcarp** [comment]
According to npm there are 616 projects directly depending on this package:
https://www.npmjs.com/package/abab?activeTab=dependents

Most of the dependencies are not imported in code (probably mistaken). Of the ones that are, it looks like it's for polyfills (example [1](https://gitlab.com/rainbird-ai/sdk-js/-/blob/master/packages/base/lib/polyfill.js#L4), [2](https://github.com/RangerMauve/webrun/blob/e34de5e0d8dc169091bdf84ec9b3a94312abe0e1/src/plugins/browser.js#L40)).

Are the Node.js native `atob`/`btoa` implementations a perfect replacement for this library or does the functionality differ slightly? If yes then let's deprecate. If no I'm happy to keep an eye on it outside the org.

**Comment by domenic** [comment]
> According to npm there are 616 projects directly depending on this package:

I wish that tab was usable. Whenever I look into the package.json's of the projects listed there, I have a hard time finding actual direct dependents. My guess is it also lists indirect dependents? Good job finding a few direct dependents though!

> Are the Node.js native `atob`/`btoa` implementations a perfect replacement for this library or does the functionality differ slightly?

There is one difference which is that Node's throw `DOMException` objects, instead of returning null. (Discussed in #87.)

**Comment by jeffcarp** [comment]
Oh interesting, the first 10 out of 10 links on that page have `abab` in their package.json (at least when browsing the files on npmjs.com). Maybe people are using a tool to flatten their deps?

> There is one difference which is that Node's throw DOMException objects

Via https://github.com/jsdom/abab/issues/87#issuecomment-1570668276 do NodeJS's `DOMException` objects work with jsdom now?

If `DOMException` is the only difference, since there's an easy workaround there I'm in favor of deprecating 👍

**Comment by domenic** [comment]
> Via [#87 (comment)](https://github.com/jsdom/abab/issues/87#issuecomment-1570668276) do NodeJS's `DOMException` objects work with jsdom now?

No, there's one global `DOMException` for all of Node.js, whereas we need per-`JSDOM` instance `DOMException`s for `JSDOM` (since each `JSDOM` is a different `Window`).

> If `DOMException` is the only difference, since there's an easy workaround there I'm in favor of deprecating 👍

Sounds good!

**Comment by domenic** [comment]
Hmm, I updated all the docs, but I don't have publish permissions. @jeffcarp could you run the following?

```
npm deprecate abab "Use your platform's native atob() and btoa() methods instead"
```

**Comment by jeffcarp** [comment]
Done: https://www.npmjs.com/package/abab thanks!
