### ISSUE TITLE
Internet Explorer has a specific behavior in some cases

### ISSUE THREAD

**Issue by just-boris** [jsdom/abab#9]
As found in #8 It throws exception when other browsers don't.

Examples:

" abcd": it should be encoded as "i·\u001d" 
"ab cd": it should be encoded as "i·\u001d" 

IE throws Exception while trying to encode it.

**Comment by jeffcarp** [comment]
Just to clarify, this is for `atob`. Unicode `\u001d` is "information separator three / group separator (GS)" according to [this chart](http://www.unicode.org/charts/PDF/U0000.pdf). Not sure if that helps but maybe IE has a problem with it?
